# Generated by Django 3.2.19 on 2023-06-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True, verbose_name='Name')),
                ('description', models.TextField(blank=True, max_length=256, null=True, verbose_name='Description')),
                ('price', models.PositiveIntegerField(verbose_name='Price')),
                ('type', models.CharField(choices=[('Main', 'Main'), ('Side and Salad', 'Side and Salad'), ('Drink', 'Drink')], max_length=32, verbose_name='Type')),
                ('picture', models.ImageField(blank=True, null=True, upload_to='foods', verbose_name='Picture')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
            ],
            options={
                'verbose_name': 'Food',
                'verbose_name_plural': 'Foods',
                'ordering': ['type'],
            },
        ),
    ]
