# Generated by Django 3.2.19 on 2023-06-20 11:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='food',
            name='type',
            field=models.CharField(blank=True, choices=[('Dish', 'Dish'), ('Side Dish', 'Side Dish'), ('Beverage', 'Beverage'), ('Dessert', 'Dessert')], max_length=32, null=True, verbose_name='Type'),
        ),
        migrations.AddField(
            model_name='food',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated'),
        ),
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(max_length=256, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='food',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='foods', verbose_name='Picture'),
        ),
    ]
