# Generated by Django 3.2.19 on 2023-06-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0002_auto_20230620_1139'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='food',
            options={'ordering': ['type'], 'verbose_name': 'Food', 'verbose_name_plural': 'Foods'},
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(blank=True, choices=[('Dish', 'Dish'), ('Side Dish', 'Side Dish'), ('Drink', 'Drink'), ('Dessert', 'Dessert')], max_length=32, null=True, verbose_name='Type'),
        ),
    ]
