# Generated by Django 3.2.19 on 2023-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20230620_1144'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='price',
            field=models.PositiveIntegerField(default=1, verbose_name='Price'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='food',
            name='name',
            field=models.CharField(max_length=32, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='food',
            name='type',
            field=models.CharField(blank=True, choices=[('Main', 'Main'), ('Side and Salad', 'Side and Salad'), ('Drink', 'Drink')], max_length=32, null=True, verbose_name='Type'),
        ),
    ]
