# Generated by Django 3.2.19 on 2023-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20230630_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='description',
            field=models.TextField(blank=True, max_length=256, null=True, verbose_name='Description'),
        ),
    ]
