# Generated by Django 3.2.19 on 2023-06-30 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('foods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Date')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Updated')),
                ('breakfast', models.ManyToManyField(blank=True, related_name='breakfast_menus', to='foods.Food')),
                ('dinner', models.ManyToManyField(blank=True, related_name='dinner_menus', to='foods.Food')),
                ('evening', models.ManyToManyField(blank=True, related_name='evening_menus', to='foods.Food')),
                ('lunch', models.ManyToManyField(blank=True, related_name='lunch_menus', to='foods.Food')),
            ],
            options={
                'verbose_name': 'Menu',
                'verbose_name_plural': 'Menus',
            },
        ),
    ]
