# Generated by Django 3.2.19 on 2023-06-20 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20230620_1144'),
        ('menus', '0002_auto_20230620_1146'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='breakfast',
            field=models.ManyToManyField(to='foods.Food'),
        ),
    ]
