# Generated by Django 3.2.19 on 2023-06-20 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0003_auto_20230620_1144'),
        ('menus', '0003_menu_breakfast'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='dinner',
            field=models.ManyToManyField(related_name='dinner_menus', to='foods.Food'),
        ),
        migrations.AddField(
            model_name='menu',
            name='lunch',
            field=models.ManyToManyField(related_name='lunch_menus', to='foods.Food'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.ManyToManyField(related_name='breakfast_menus', to='foods.Food'),
        ),
    ]
