# Generated by Django 3.2.19 on 2023-06-30 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0004_auto_20230630_1527'),
        ('menus', '0004_auto_20230620_1149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='breakfast',
            field=models.ManyToManyField(blank=True, related_name='breakfast_menus', to='foods.Food'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='dinner',
            field=models.ManyToManyField(blank=True, related_name='dinner_menus', to='foods.Food'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='lunch',
            field=models.ManyToManyField(blank=True, related_name='lunch_menus', to='foods.Food'),
        ),
    ]
