# Generated by Django 3.2.19 on 2023-06-30 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0005_alter_food_description'),
        ('menus', '0005_auto_20230630_1527'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='evening',
            field=models.ManyToManyField(blank=True, related_name='evening_menus', to='foods.Food'),
        ),
    ]
